<?php

use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\TermsController;
use Tabuna\Breadcrumbs\Trail;

/*
 * Frontend Controllers
 * All route names are prefixed with 'frontend.'.
 */
Route::get('/', [HomeController::class, 'index'])
    ->name('index')
    ->breadcrumbs(function (Trail $trail) {
        $trail->push(__('Home'), route('frontend.index'));
    });

Route::get('terms', [TermsController::class, 'index'])
    ->name('pages.terms')
    ->breadcrumbs(function (Trail $trail) {
        $trail->parent('frontend.index')
            ->push(__('Terms & Conditions'), route('frontend.pages.terms'));
    });


// Search Route
Route::get('search', [HomeController::class, 'search'])->name('search');

//feed url
Route::get('/feed', function () {
    // now we are serving file generated by command
    if (!file_exists(storage_path('app/feed/latest-posts.xml'))) {
        abort(404);
    }
    return Response::file(storage_path('app/feed/latest-posts.xml'), ['Content-Type' => 'application/rss+xml; charset=UTF-8']);
})->name('feed');
//post comment feed route
Route::get('{slug}/feed', function ($slug) {
    $post = \App\Models\Blog\Post::where('slug', '=', $slug)->first();
    if ($post) {
        $feed = new \StdClass();
        $feed->build_date = Carbon::now()->toRfc1123String();
        return response()->view('frontend.feed.comments', [
            'post' => $post, 'feed' => $feed
        ])->header('Content-Type', 'text/xml');
    }
    abort(404);
})->name('single-feed');


// Author Route
Route::get('author/{username}', [HomeController::class, 'singleAuthor'])->middleware('cacheResponse:1500')->name('single-author');

// Category Route
Route::get('category/{slug}', [HomeController::class, 'singleCategory'])->middleware('cacheResponse:1500')->name('single-category');
// All category Route
Route::get('categories', [HomeController::class, 'categories'])->name('categories');

// Latest posts Route
Route::get('latest-posts', [HomeController::class, 'latestPosts'])->middleware('cacheResponse:1500')
    ->name('latest-posts');
// Post Route
Route::get('{slug}', [HomeController::class, 'singlePost'])->middleware('cacheResponse')->name('single-post');
// Page Route
Route::any('{slug?}', [HomeController::class, 'singlePage'])->middleware('cacheResponse')->name('single-page');
